-- https://school.programmers.co.kr/learn/courses/30/lessons/59412
-- 보호소에서는 몇 시에 입양이 가장 활발하게 일어나는지 알아보려 합니다. 09:00부터 19:59까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회하는 SQL문
SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT 
FROM ANIMAL_OUTS 
WHERE HOUR(DATETIME) 
IN (SELECT B.TIME FROM (SELECT HOUR(DATETIME) AS TIME FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME)) B 
WHERE B.TIME >= 9) GROUP BY HOUR(DATETIME) ORDER BY HOUR(DATETIME) ASC;